//! Versions every file in `public/`, the way cargo-leptos versions its own.
//!
//! cargo-leptos puts a content hash in the names of the bundle and the
//! stylesheet, so production can cache them for a year. The files in
//! `public/` keep their names, so a changed icon or font would stay cached
//! for a year too. This script hashes each file's bytes (FNV-1a, 64 bits,
//! no new crate) and writes one Rust constant per file into
//! `$OUT_DIR/public_assets.rs`:
//!
//! ```text
//! pub const FONTS_INTER_REGULAR_WOFF2: &str = "/fonts/Inter-Regular.woff2?v=<hash>";
//! ```
//!
//! `src/paths.rs` includes it. Rust code links a file only through these
//! constants, so a file that is renamed or removed fails the compile. The
//! stylesheet and the web manifest are static files that can't read them;
//! they carry the same `?v=<hash>` written out, and a test in
//! `src/paths.rs` fails with the value to paste when a file changes.
//!
//! Cargo reruns this when anything in `public/` changes, and the binary and
//! `site/` of a deploy come from the same checkout, so the hashes in the
//! binary always match the files it serves.

use std::{
    env,
    fmt::Write as _,
    fs,
    path::{Path, PathBuf},
};

const PUBLIC: &str = "public";

const FNV_OFFSET: u64 = 0xcbf2_9ce4_8422_2325;
const FNV_PRIME: u64 = 0x0100_0000_01b3;

fn fnv1a(bytes: &[u8]) -> u64 {
    let mut hash = FNV_OFFSET;
    for byte in bytes {
        hash ^= u64::from(*byte);
        hash = hash.wrapping_mul(FNV_PRIME);
    }
    hash
}

/// Every file under `dir`, recursively.
fn files(dir: &Path, out: &mut Vec<PathBuf>) {
    let Ok(entries) = fs::read_dir(dir) else {
        return;
    };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            files(&path, out);
        } else if path.file_name().is_some_and(|name| name != ".DS_Store") {
            out.push(path);
        }
    }
}

/// `fonts/Inter-Regular.woff2` -> `FONTS_INTER_REGULAR_WOFF2`.
fn const_name(relative: &str) -> String {
    let name: String = relative
        .chars()
        .map(|c| {
            if c.is_ascii_alphanumeric() {
                c.to_ascii_uppercase()
            } else {
                '_'
            }
        })
        .collect();
    if name.starts_with(|c: char| c.is_ascii_digit()) {
        format!("N{name}")
    } else {
        name
    }
}

fn main() {
    println!("cargo:rerun-if-changed={PUBLIC}");
    let mut all = Vec::new();
    files(Path::new(PUBLIC), &mut all);
    // Sorted, so the generated file doesn't depend on the order the disk
    // lists files.
    all.sort();

    let mut consts = String::from("// Generated by build.rs from public/. Don't edit.\n");
    let mut table = String::from("pub const ALL: &[(&str, &str)] = &[\n");
    for path in &all {
        let relative = path
            .strip_prefix(PUBLIC)
            .expect("under public/")
            .to_string_lossy()
            .replace('\\', "/");
        let bytes = fs::read(path)
            .unwrap_or_else(|e| panic!("build.rs: cannot read {}: {e}", path.display()));
        let url = format!("/{relative}?v={:016x}", fnv1a(&bytes));
        let name = const_name(&relative);
        let _ = writeln!(consts, "pub const {name}: &str = {url:?};");
        let _ = writeln!(table, "    ({:?}, {name}),", format!("/{relative}"));
    }
    table.push_str("];\n");

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("public_assets.rs");
    fs::write(&out, consts + &table)
        .unwrap_or_else(|e| panic!("build.rs: cannot write {}: {e}", out.display()));
}
