//! Addresses of the files in `public/`, each with `?v=<hash>` of its own
//! bytes appended. `build.rs` computes the hashes at compile time and
//! generates one constant per file in modules that follow the folders
//! ([`assets`]): `assets::FAVICON_ICO`,
//! `assets::favicon::APPLE_TOUCH_ICON_PNG`. Drop a file anywhere in `public/`
//! and its constant exists at the next build; replace it and only its own
//! `?v=` changes, so browsers re-fetch just that file despite the year-long
//! cache. Rust code links files only through these constants, so a file
//! that is renamed or removed fails the compile, and `tests/requests/links.rs`
//! fails on a page that links a `public/` file as a plain string.
//!
//! The stylesheet can't read the constants. If it ever names a `public/`
//! file (a self-hosted font, a background image), it writes the same
//! `?v=<hash>` out, and a test below fails with the value to paste when the
//! file changes.
//!
//! The one address that can't carry a version is `/favicon.ico` at the
//! root: browsers ask for it by that exact name, and only when a page links
//! no icon, which ours always do.

/// One constant per file in `public/`, in modules that follow the folders,
/// plus [`assets::ALL`], every plain path with its versioned URL.
/// Generated by `build.rs`.
pub mod assets {
    include!(concat!(env!("OUT_DIR"), "/public_assets.rs"));
}

pub const FAVICON: &str = assets::favicon::FAVICON_ICO;
pub const FAVICON_32: &str = assets::favicon::FAVICON_32X32_PNG;
pub const FAVICON_16: &str = assets::favicon::FAVICON_16X16_PNG;
pub const APPLE_TOUCH_ICON: &str = assets::favicon::APPLE_TOUCH_ICON_PNG;

/// The web manifest. A route, not a file (controllers/manifest.rs): built
/// from `APP_NAME`, the colours and the icon constants above, so it carries
/// no `?v=` of its own.
pub const MANIFEST: &str = "/manifest.webmanifest";

/// The versioned URL of a plain `public/` path such as
/// `/favicon/favicon.ico`, or `None` when no such file exists.
#[must_use]
pub fn versioned(path: &str) -> Option<&'static str> {
    assets::ALL
        .iter()
        .find(|(plain, _)| *plain == path)
        .map(|(_, url)| *url)
}

#[cfg(test)]
mod tests {
    use std::{fs, path::Path};

    use super::*;

    fn root() -> &'static Path {
        Path::new(env!("CARGO_MANIFEST_DIR"))
    }

    #[test]
    fn every_generated_address_is_a_file_with_a_16_hex_version() {
        assert!(!assets::ALL.is_empty());
        for (plain, url) in assets::ALL {
            assert!(
                root().join("public").join(&plain[1..]).is_file(),
                "{plain} is not a file in public/"
            );
            let version = url
                .strip_prefix(*plain)
                .and_then(|rest| rest.strip_prefix("?v="))
                .unwrap_or_else(|| panic!("{url} is not {plain}?v=<hash>"));
            assert_eq!(version.len(), 16, "{url}");
            assert!(version.chars().all(|c| c.is_ascii_hexdigit()), "{url}");
        }
    }

    /// Every `url(/...)` in the stylesheet must be the current versioned URL
    /// of its `public/` file; the failure names the value to write. None
    /// today: Tailwind's defaults name no file.
    #[test]
    fn the_stylesheet_names_public_files_with_their_current_version() {
        let css = fs::read_to_string(root().join("style/tailwind.css")).expect("the stylesheet");
        let urls = css
            .split("url(")
            .skip(1)
            .filter_map(|rest| rest.split(')').next())
            .map(|url| url.trim().trim_matches(['"', '\'']))
            .filter(|url| url.starts_with('/'));
        for url in urls {
            let plain = url.split('?').next().unwrap_or_default();
            let expected = versioned(plain)
                .unwrap_or_else(|| panic!("style/tailwind.css: {plain} is not a file in public/"));
            assert_eq!(
                url, expected,
                "style/tailwind.css: {plain} changed or isn't versioned; write it as {expected}"
            );
        }
    }
}
