//! Addresses of the files in `public/`, each with `?v=<hash>` of its own
//! bytes appended. `build.rs` computes the hashes at compile time and
//! generates one constant per file ([`generated`]): replace a file, build,
//! and every link to it is a new URL, so a browser fetches it once despite
//! the year-long cache. Rust code links files only through these constants,
//! so a file that is renamed or removed fails the compile.
//!
//! Two static files name `public/` files themselves and can't read the
//! constants: `style/tailwind.css` (the fonts) and
//! `public/favicon/site.webmanifest` (the Android icons). They carry the
//! same `?v=<hash>` written out, and the tests below fail with the value to
//! paste when a file changes.
//!
//! The one address that can't carry a version is `/favicon.ico` at the
//! root: browsers ask for it by that exact name, and only when a page links
//! no icon, which ours always do.

/// One constant per file in `public/`, plus [`generated::ALL`], the table
/// of every plain path and its versioned URL. Generated by `build.rs`.
pub mod generated {
    include!(concat!(env!("OUT_DIR"), "/public_assets.rs"));
}

pub const FAVICON: &str = generated::FAVICON_FAVICON_ICO;
pub const FAVICON_32: &str = generated::FAVICON_FAVICON_32X32_PNG;
pub const FAVICON_16: &str = generated::FAVICON_FAVICON_16X16_PNG;
pub const APPLE_TOUCH_ICON: &str = generated::FAVICON_APPLE_TOUCH_ICON_PNG;
pub const MANIFEST: &str = generated::FAVICON_SITE_WEBMANIFEST;
/// Preloaded by the shell; must be the exact URL the stylesheet's
/// `@font-face` uses, `?v=` included, or the browser downloads it twice.
pub const FONT_INTER_REGULAR: &str = generated::FONTS_INTER_REGULAR_WOFF2;

/// The versioned URL of a plain `public/` path such as
/// `/fonts/Inter-Bold.woff2`, or `None` when no such file exists.
#[must_use]
pub fn versioned(path: &str) -> Option<&'static str> {
    generated::ALL
        .iter()
        .find(|(plain, _)| *plain == path)
        .map(|(_, url)| *url)
}

#[cfg(test)]
mod tests {
    use std::{fs, path::Path};

    use super::*;

    fn read(file: &str) -> String {
        fs::read_to_string(Path::new(env!("CARGO_MANIFEST_DIR")).join(file))
            .unwrap_or_else(|e| panic!("{file}: {e}"))
    }

    /// The `public/` addresses a static file names, as written.
    fn named_in(text: &str, open: &str, close: char) -> Vec<String> {
        text.split(open)
            .skip(1)
            .filter_map(|rest| rest.split(close).next())
            .map(|url| url.trim().trim_matches(['"', '\'']).to_string())
            .filter(|url| url.starts_with('/'))
            .collect()
    }

    /// Each address must be the current versioned URL of its file.
    fn assert_current(file: &str, urls: &[String]) {
        assert!(!urls.is_empty(), "{file}: no addresses found");
        for url in urls {
            let plain = url.split('?').next().unwrap_or_default();
            let expected = versioned(plain)
                .unwrap_or_else(|| panic!("{file}: {plain} is not a file in public/"));
            assert_eq!(
                url, expected,
                "{file}: {plain} changed or isn't versioned; write it as {expected}"
            );
        }
    }

    #[test]
    fn every_public_file_has_a_16_hex_version() {
        assert!(!generated::ALL.is_empty());
        for (plain, url) in generated::ALL {
            let version = url
                .strip_prefix(*plain)
                .and_then(|rest| rest.strip_prefix("?v="))
                .unwrap_or_else(|| panic!("{url} is not {plain}?v=<hash>"));
            assert_eq!(version.len(), 16, "{url}");
            assert!(version.chars().all(|c| c.is_ascii_hexdigit()), "{url}");
        }
    }

    #[test]
    fn the_stylesheet_names_the_current_font_versions() {
        let css = read("style/tailwind.css");
        let fonts = named_in(&css, "url(", ')');
        assert_current("style/tailwind.css", &fonts);
        assert!(
            fonts.iter().any(|url| url == FONT_INTER_REGULAR),
            "the shell preloads {FONT_INTER_REGULAR}, which the stylesheet must use as written"
        );
    }

    #[test]
    fn the_manifest_names_the_current_icon_versions() {
        let manifest = read("public/favicon/site.webmanifest");
        assert_current(
            "public/favicon/site.webmanifest",
            &named_in(&manifest, "\"src\":", ','),
        );
    }
}
